// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: busi_pb.proto

#ifndef PROTOBUF_INCLUDED_busi_5fpb_2eproto
#define PROTOBUF_INCLUDED_busi_5fpb_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_busi_5fpb_2eproto 

namespace protobuf_busi_5fpb_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_busi_5fpb_2eproto
namespace xy {
class SimpleCodec;
class SimpleCodecDefaultTypeInternal;
extern SimpleCodecDefaultTypeInternal _SimpleCodec_default_instance_;
}  // namespace xy
namespace google {
namespace protobuf {
template<> ::xy::SimpleCodec* Arena::CreateMaybeMessage<::xy::SimpleCodec>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace xy {

// ===================================================================

class SimpleCodec : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xy.SimpleCodec) */ {
 public:
  SimpleCodec();
  virtual ~SimpleCodec();

  SimpleCodec(const SimpleCodec& from);

  inline SimpleCodec& operator=(const SimpleCodec& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SimpleCodec(SimpleCodec&& from) noexcept
    : SimpleCodec() {
    *this = ::std::move(from);
  }

  inline SimpleCodec& operator=(SimpleCodec&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SimpleCodec& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SimpleCodec* internal_default_instance() {
    return reinterpret_cast<const SimpleCodec*>(
               &_SimpleCodec_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SimpleCodec* other);
  friend void swap(SimpleCodec& a, SimpleCodec& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SimpleCodec* New() const final {
    return CreateMaybeMessage<SimpleCodec>(NULL);
  }

  SimpleCodec* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SimpleCodec>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SimpleCodec& from);
  void MergeFrom(const SimpleCodec& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimpleCodec* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional uint32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:xy.SimpleCodec)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_name();
  void clear_has_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 id_;
  friend struct ::protobuf_busi_5fpb_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SimpleCodec

// optional uint32 id = 1;
inline bool SimpleCodec::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SimpleCodec::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SimpleCodec::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SimpleCodec::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 SimpleCodec::id() const {
  // @@protoc_insertion_point(field_get:xy.SimpleCodec.id)
  return id_;
}
inline void SimpleCodec::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:xy.SimpleCodec.id)
}

// optional string name = 2;
inline bool SimpleCodec::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SimpleCodec::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SimpleCodec::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SimpleCodec::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& SimpleCodec::name() const {
  // @@protoc_insertion_point(field_get:xy.SimpleCodec.name)
  return name_.GetNoArena();
}
inline void SimpleCodec::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:xy.SimpleCodec.name)
}
#if LANG_CXX11
inline void SimpleCodec::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:xy.SimpleCodec.name)
}
#endif
inline void SimpleCodec::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:xy.SimpleCodec.name)
}
inline void SimpleCodec::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:xy.SimpleCodec.name)
}
inline ::std::string* SimpleCodec::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:xy.SimpleCodec.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SimpleCodec::release_name() {
  // @@protoc_insertion_point(field_release:xy.SimpleCodec.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SimpleCodec::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:xy.SimpleCodec.name)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace xy

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_busi_5fpb_2eproto
