// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#include "common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_common_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_common_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_RequestPacket_ContextEntry_DoNotUse;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_common_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ResponsePacket_ContextEntry_DoNotUse;
}  // namespace protobuf_common_2eproto
namespace xy {
class InfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Info>
      _instance;
} _Info_default_instance_;
class RequestPacket_ContextEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RequestPacket_ContextEntry_DoNotUse>
      _instance;
} _RequestPacket_ContextEntry_DoNotUse_default_instance_;
class RequestPacketDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RequestPacket>
      _instance;
} _RequestPacket_default_instance_;
class ResponsePacket_ContextEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResponsePacket_ContextEntry_DoNotUse>
      _instance;
} _ResponsePacket_ContextEntry_DoNotUse_default_instance_;
class ResponsePacketDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ResponsePacket>
      _instance;
} _ResponsePacket_default_instance_;
}  // namespace xy
namespace protobuf_common_2eproto {
static void InitDefaultsInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::xy::_Info_default_instance_;
    new (ptr) ::xy::Info();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::xy::Info::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Info =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsInfo}, {}};

static void InitDefaultsRequestPacket_ContextEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::xy::_RequestPacket_ContextEntry_DoNotUse_default_instance_;
    new (ptr) ::xy::RequestPacket_ContextEntry_DoNotUse();
  }
  ::xy::RequestPacket_ContextEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RequestPacket_ContextEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRequestPacket_ContextEntry_DoNotUse}, {}};

static void InitDefaultsRequestPacket() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::xy::_RequestPacket_default_instance_;
    new (ptr) ::xy::RequestPacket();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::xy::RequestPacket::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_RequestPacket =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsRequestPacket}, {
      &protobuf_common_2eproto::scc_info_RequestPacket_ContextEntry_DoNotUse.base,}};

static void InitDefaultsResponsePacket_ContextEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::xy::_ResponsePacket_ContextEntry_DoNotUse_default_instance_;
    new (ptr) ::xy::ResponsePacket_ContextEntry_DoNotUse();
  }
  ::xy::ResponsePacket_ContextEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ResponsePacket_ContextEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsResponsePacket_ContextEntry_DoNotUse}, {}};

static void InitDefaultsResponsePacket() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::xy::_ResponsePacket_default_instance_;
    new (ptr) ::xy::ResponsePacket();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::xy::ResponsePacket::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ResponsePacket =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsResponsePacket}, {
      &protobuf_common_2eproto::scc_info_ResponsePacket_ContextEntry_DoNotUse.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Info.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RequestPacket_ContextEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RequestPacket.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ResponsePacket_ContextEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ResponsePacket.base);
}

::google::protobuf::Metadata file_level_metadata[5];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::Info, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::Info, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::Info, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::Info, name_),
  1,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket_ContextEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket_ContextEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket_ContextEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket_ContextEntry_DoNotUse, value_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket, iversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket, irequestid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket, sfuncname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket, cpackettype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket, sbuffer_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket, itimeoutms_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::RequestPacket, context_),
  2,
  3,
  0,
  4,
  1,
  5,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket_ContextEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket_ContextEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket_ContextEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket_ContextEntry_DoNotUse, value_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket, iversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket, irequestid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket, cpackettype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket, sbuffer_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket, iretcode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket, sretdesc_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::xy::ResponsePacket, context_),
  2,
  3,
  4,
  0,
  5,
  1,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::xy::Info)},
  { 9, 16, sizeof(::xy::RequestPacket_ContextEntry_DoNotUse)},
  { 18, 30, sizeof(::xy::RequestPacket)},
  { 37, 44, sizeof(::xy::ResponsePacket_ContextEntry_DoNotUse)},
  { 46, 58, sizeof(::xy::ResponsePacket)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::xy::_Info_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::xy::_RequestPacket_ContextEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::xy::_RequestPacket_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::xy::_ResponsePacket_ContextEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::xy::_ResponsePacket_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "common.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014common.proto\022\002xy\" \n\004Info\022\n\n\002id\030\001 \001(\r\022\014"
      "\n\004name\030\002 \001(\t\"\343\001\n\rRequestPacket\022\020\n\010iVersi"
      "on\030\001 \001(\r\022\022\n\niRequestId\030\002 \001(\r\022\021\n\tsFuncNam"
      "e\030\003 \001(\t\022\023\n\013cPacketType\030\004 \001(\r\022\017\n\007sBuffer\030"
      "\005 \001(\014\022\022\n\niTimeoutMs\030\006 \001(\r\022/\n\007context\030\007 \003"
      "(\0132\036.xy.RequestPacket.ContextEntry\032.\n\014Co"
      "ntextEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002"
      "8\001\"\342\001\n\016ResponsePacket\022\020\n\010iVersion\030\001 \001(\r\022"
      "\022\n\niRequestId\030\002 \001(\r\022\023\n\013cPacketType\030\003 \001(\r"
      "\022\017\n\007sBuffer\030\004 \001(\014\022\020\n\010iRetCode\030\005 \001(\005\022\020\n\010s"
      "RetDesc\030\006 \001(\t\0220\n\007context\030\007 \003(\0132\037.xy.Resp"
      "onsePacket.ContextEntry\032.\n\014ContextEntry\022"
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*J\n\tECall"
      "Type\022\022\n\016ECallType_Sync\020\000\022\023\n\017ECallType_As"
      "ync\020\001\022\024\n\020ECallType_OneWay\020\002*:\n\014EPackageT"
      "ype\022\023\n\017EPackageType_Pb\020\000\022\025\n\021EPackageType"
      "_Json\020\001*\200\001\n\010ERetCode\022\037\n\022ERetCode_UNKnowE"
      "rr\020\366\377\377\377\377\377\377\377\377\001\022\036\n\021ERetCode_Overload\020\367\377\377\377\377"
      "\377\377\377\377\001\022 \n\023ERetCode_UNKnowFunc\020\377\377\377\377\377\377\377\377\377\001\022"
      "\021\n\rERetCode_SUCC\020\000*k\n\nEReqStatus\022\024\n\020EReq"
      "Status_Doing\020\000\022\025\n\021EReqStatus_Finish\020\001\022\026\n"
      "\022EReqStatus_Timeout\020\002\022\030\n\024EReqStatus_Exce"
      "ption\020\003"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 887);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "common.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_common_2eproto
namespace xy {
const ::google::protobuf::EnumDescriptor* ECallType_descriptor() {
  protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2eproto::file_level_enum_descriptors[0];
}
bool ECallType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* EPackageType_descriptor() {
  protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2eproto::file_level_enum_descriptors[1];
}
bool EPackageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ERetCode_descriptor() {
  protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2eproto::file_level_enum_descriptors[2];
}
bool ERetCode_IsValid(int value) {
  switch (value) {
    case -10:
    case -9:
    case -1:
    case 0:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* EReqStatus_descriptor() {
  protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_common_2eproto::file_level_enum_descriptors[3];
}
bool EReqStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void Info::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Info::kIdFieldNumber;
const int Info::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Info::Info()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_common_2eproto::scc_info_Info.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:xy.Info)
}
Info::Info(const Info& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:xy.Info)
}

void Info::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0u;
}

Info::~Info() {
  // @@protoc_insertion_point(destructor:xy.Info)
  SharedDtor();
}

void Info::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Info::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Info::descriptor() {
  ::protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_common_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Info& Info::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_common_2eproto::scc_info_Info.base);
  return *internal_default_instance();
}


void Info::Clear() {
// @@protoc_insertion_point(message_clear_start:xy.Info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    name_.ClearNonDefaultToEmptyNoArena();
  }
  id_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Info::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:xy.Info)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "xy.Info.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:xy.Info)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:xy.Info)
  return false;
#undef DO_
}

void Info::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:xy.Info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 id = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // optional string name = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "xy.Info.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:xy.Info)
}

::google::protobuf::uint8* Info::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:xy.Info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 id = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // optional string name = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "xy.Info.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xy.Info)
  return target;
}

size_t Info::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xy.Info)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional string name = 2;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Info::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:xy.Info)
  GOOGLE_DCHECK_NE(&from, this);
  const Info* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Info>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:xy.Info)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:xy.Info)
    MergeFrom(*source);
  }
}

void Info::MergeFrom(const Info& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:xy.Info)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      id_ = from.id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Info::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:xy.Info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Info::CopyFrom(const Info& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xy.Info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Info::IsInitialized() const {
  return true;
}

void Info::Swap(Info* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Info::InternalSwap(Info* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(id_, other->id_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Info::GetMetadata() const {
  protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_common_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

RequestPacket_ContextEntry_DoNotUse::RequestPacket_ContextEntry_DoNotUse() {}
RequestPacket_ContextEntry_DoNotUse::RequestPacket_ContextEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void RequestPacket_ContextEntry_DoNotUse::MergeFrom(const RequestPacket_ContextEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata RequestPacket_ContextEntry_DoNotUse::GetMetadata() const {
  ::protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_common_2eproto::file_level_metadata[1];
}
void RequestPacket_ContextEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void RequestPacket::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RequestPacket::kIVersionFieldNumber;
const int RequestPacket::kIRequestIdFieldNumber;
const int RequestPacket::kSFuncNameFieldNumber;
const int RequestPacket::kCPacketTypeFieldNumber;
const int RequestPacket::kSBufferFieldNumber;
const int RequestPacket::kITimeoutMsFieldNumber;
const int RequestPacket::kContextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RequestPacket::RequestPacket()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_common_2eproto::scc_info_RequestPacket.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:xy.RequestPacket)
}
RequestPacket::RequestPacket(const RequestPacket& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  context_.MergeFrom(from.context_);
  sfuncname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_sfuncname()) {
    sfuncname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sfuncname_);
  }
  sbuffer_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_sbuffer()) {
    sbuffer_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sbuffer_);
  }
  ::memcpy(&iversion_, &from.iversion_,
    static_cast<size_t>(reinterpret_cast<char*>(&itimeoutms_) -
    reinterpret_cast<char*>(&iversion_)) + sizeof(itimeoutms_));
  // @@protoc_insertion_point(copy_constructor:xy.RequestPacket)
}

void RequestPacket::SharedCtor() {
  sfuncname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sbuffer_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&iversion_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&itimeoutms_) -
      reinterpret_cast<char*>(&iversion_)) + sizeof(itimeoutms_));
}

RequestPacket::~RequestPacket() {
  // @@protoc_insertion_point(destructor:xy.RequestPacket)
  SharedDtor();
}

void RequestPacket::SharedDtor() {
  sfuncname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sbuffer_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RequestPacket::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RequestPacket::descriptor() {
  ::protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_common_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RequestPacket& RequestPacket::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_common_2eproto::scc_info_RequestPacket.base);
  return *internal_default_instance();
}


void RequestPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:xy.RequestPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  context_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      sfuncname_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      sbuffer_.ClearNonDefaultToEmptyNoArena();
    }
  }
  if (cached_has_bits & 60u) {
    ::memset(&iversion_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&itimeoutms_) -
        reinterpret_cast<char*>(&iversion_)) + sizeof(itimeoutms_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool RequestPacket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:xy.RequestPacket)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 iVersion = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_iversion();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &iversion_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 iRequestId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_irequestid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &irequestid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string sFuncName = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sfuncname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->sfuncname().data(), static_cast<int>(this->sfuncname().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "xy.RequestPacket.sFuncName");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 cPacketType = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_cpackettype();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &cpackettype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes sBuffer = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_sbuffer()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 iTimeoutMs = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          set_has_itimeoutms();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &itimeoutms_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> context = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          RequestPacket_ContextEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              RequestPacket_ContextEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&context_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "xy.RequestPacket.ContextEntry.key");
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "xy.RequestPacket.ContextEntry.value");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:xy.RequestPacket)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:xy.RequestPacket)
  return false;
#undef DO_
}

void RequestPacket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:xy.RequestPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 iVersion = 1;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->iversion(), output);
  }

  // optional uint32 iRequestId = 2;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->irequestid(), output);
  }

  // optional string sFuncName = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sfuncname().data(), static_cast<int>(this->sfuncname().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "xy.RequestPacket.sFuncName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->sfuncname(), output);
  }

  // optional uint32 cPacketType = 4;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->cpackettype(), output);
  }

  // optional bytes sBuffer = 5;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->sbuffer(), output);
  }

  // optional uint32 iTimeoutMs = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->itimeoutms(), output);
  }

  // map<string, string> context = 7;
  if (!this->context().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormat::SERIALIZE,
          "xy.RequestPacket.ContextEntry.key");
        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormat::SERIALIZE,
          "xy.RequestPacket.ContextEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->context().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->context().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->context().begin();
          it != this->context().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<RequestPacket_ContextEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(context_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            7, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<RequestPacket_ContextEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->context().begin();
          it != this->context().end(); ++it) {
        entry.reset(context_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            7, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:xy.RequestPacket)
}

::google::protobuf::uint8* RequestPacket::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:xy.RequestPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 iVersion = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->iversion(), target);
  }

  // optional uint32 iRequestId = 2;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->irequestid(), target);
  }

  // optional string sFuncName = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sfuncname().data(), static_cast<int>(this->sfuncname().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "xy.RequestPacket.sFuncName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->sfuncname(), target);
  }

  // optional uint32 cPacketType = 4;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->cpackettype(), target);
  }

  // optional bytes sBuffer = 5;
  if (cached_has_bits & 0x00000002u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->sbuffer(), target);
  }

  // optional uint32 iTimeoutMs = 6;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->itimeoutms(), target);
  }

  // map<string, string> context = 7;
  if (!this->context().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormat::SERIALIZE,
          "xy.RequestPacket.ContextEntry.key");
        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormat::SERIALIZE,
          "xy.RequestPacket.ContextEntry.value");
      }
    };

    if (deterministic &&
        this->context().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->context().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->context().begin();
          it != this->context().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<RequestPacket_ContextEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(context_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       7, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<RequestPacket_ContextEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->context().begin();
          it != this->context().end(); ++it) {
        entry.reset(context_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       7, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xy.RequestPacket)
  return target;
}

size_t RequestPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xy.RequestPacket)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // map<string, string> context = 7;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->context_size());
  {
    ::std::unique_ptr<RequestPacket_ContextEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->context().begin();
        it != this->context().end(); ++it) {
      entry.reset(context_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  if (_has_bits_[0 / 32] & 63u) {
    // optional string sFuncName = 3;
    if (has_sfuncname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sfuncname());
    }

    // optional bytes sBuffer = 5;
    if (has_sbuffer()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->sbuffer());
    }

    // optional uint32 iVersion = 1;
    if (has_iversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->iversion());
    }

    // optional uint32 iRequestId = 2;
    if (has_irequestid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->irequestid());
    }

    // optional uint32 cPacketType = 4;
    if (has_cpackettype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->cpackettype());
    }

    // optional uint32 iTimeoutMs = 6;
    if (has_itimeoutms()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->itimeoutms());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RequestPacket::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:xy.RequestPacket)
  GOOGLE_DCHECK_NE(&from, this);
  const RequestPacket* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RequestPacket>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:xy.RequestPacket)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:xy.RequestPacket)
    MergeFrom(*source);
  }
}

void RequestPacket::MergeFrom(const RequestPacket& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:xy.RequestPacket)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  context_.MergeFrom(from.context_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_sfuncname();
      sfuncname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sfuncname_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_sbuffer();
      sbuffer_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sbuffer_);
    }
    if (cached_has_bits & 0x00000004u) {
      iversion_ = from.iversion_;
    }
    if (cached_has_bits & 0x00000008u) {
      irequestid_ = from.irequestid_;
    }
    if (cached_has_bits & 0x00000010u) {
      cpackettype_ = from.cpackettype_;
    }
    if (cached_has_bits & 0x00000020u) {
      itimeoutms_ = from.itimeoutms_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void RequestPacket::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:xy.RequestPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RequestPacket::CopyFrom(const RequestPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xy.RequestPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestPacket::IsInitialized() const {
  return true;
}

void RequestPacket::Swap(RequestPacket* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RequestPacket::InternalSwap(RequestPacket* other) {
  using std::swap;
  context_.Swap(&other->context_);
  sfuncname_.Swap(&other->sfuncname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  sbuffer_.Swap(&other->sbuffer_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(iversion_, other->iversion_);
  swap(irequestid_, other->irequestid_);
  swap(cpackettype_, other->cpackettype_);
  swap(itimeoutms_, other->itimeoutms_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RequestPacket::GetMetadata() const {
  protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_common_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

ResponsePacket_ContextEntry_DoNotUse::ResponsePacket_ContextEntry_DoNotUse() {}
ResponsePacket_ContextEntry_DoNotUse::ResponsePacket_ContextEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void ResponsePacket_ContextEntry_DoNotUse::MergeFrom(const ResponsePacket_ContextEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata ResponsePacket_ContextEntry_DoNotUse::GetMetadata() const {
  ::protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_common_2eproto::file_level_metadata[3];
}
void ResponsePacket_ContextEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void ResponsePacket::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ResponsePacket::kIVersionFieldNumber;
const int ResponsePacket::kIRequestIdFieldNumber;
const int ResponsePacket::kCPacketTypeFieldNumber;
const int ResponsePacket::kSBufferFieldNumber;
const int ResponsePacket::kIRetCodeFieldNumber;
const int ResponsePacket::kSRetDescFieldNumber;
const int ResponsePacket::kContextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ResponsePacket::ResponsePacket()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_common_2eproto::scc_info_ResponsePacket.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:xy.ResponsePacket)
}
ResponsePacket::ResponsePacket(const ResponsePacket& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  context_.MergeFrom(from.context_);
  sbuffer_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_sbuffer()) {
    sbuffer_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sbuffer_);
  }
  sretdesc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_sretdesc()) {
    sretdesc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sretdesc_);
  }
  ::memcpy(&iversion_, &from.iversion_,
    static_cast<size_t>(reinterpret_cast<char*>(&iretcode_) -
    reinterpret_cast<char*>(&iversion_)) + sizeof(iretcode_));
  // @@protoc_insertion_point(copy_constructor:xy.ResponsePacket)
}

void ResponsePacket::SharedCtor() {
  sbuffer_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sretdesc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&iversion_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&iretcode_) -
      reinterpret_cast<char*>(&iversion_)) + sizeof(iretcode_));
}

ResponsePacket::~ResponsePacket() {
  // @@protoc_insertion_point(destructor:xy.ResponsePacket)
  SharedDtor();
}

void ResponsePacket::SharedDtor() {
  sbuffer_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sretdesc_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ResponsePacket::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ResponsePacket::descriptor() {
  ::protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_common_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ResponsePacket& ResponsePacket::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_common_2eproto::scc_info_ResponsePacket.base);
  return *internal_default_instance();
}


void ResponsePacket::Clear() {
// @@protoc_insertion_point(message_clear_start:xy.ResponsePacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  context_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      sbuffer_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      sretdesc_.ClearNonDefaultToEmptyNoArena();
    }
  }
  if (cached_has_bits & 60u) {
    ::memset(&iversion_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&iretcode_) -
        reinterpret_cast<char*>(&iversion_)) + sizeof(iretcode_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ResponsePacket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:xy.ResponsePacket)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 iVersion = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_iversion();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &iversion_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 iRequestId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_irequestid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &irequestid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 cPacketType = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_cpackettype();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &cpackettype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes sBuffer = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_sbuffer()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 iRetCode = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_iretcode();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &iretcode_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string sRetDesc = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sretdesc()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->sretdesc().data(), static_cast<int>(this->sretdesc().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "xy.ResponsePacket.sRetDesc");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> context = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          ResponsePacket_ContextEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              ResponsePacket_ContextEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&context_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "xy.ResponsePacket.ContextEntry.key");
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "xy.ResponsePacket.ContextEntry.value");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:xy.ResponsePacket)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:xy.ResponsePacket)
  return false;
#undef DO_
}

void ResponsePacket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:xy.ResponsePacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 iVersion = 1;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->iversion(), output);
  }

  // optional uint32 iRequestId = 2;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->irequestid(), output);
  }

  // optional uint32 cPacketType = 3;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->cpackettype(), output);
  }

  // optional bytes sBuffer = 4;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->sbuffer(), output);
  }

  // optional int32 iRetCode = 5;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->iretcode(), output);
  }

  // optional string sRetDesc = 6;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sretdesc().data(), static_cast<int>(this->sretdesc().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "xy.ResponsePacket.sRetDesc");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->sretdesc(), output);
  }

  // map<string, string> context = 7;
  if (!this->context().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormat::SERIALIZE,
          "xy.ResponsePacket.ContextEntry.key");
        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormat::SERIALIZE,
          "xy.ResponsePacket.ContextEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->context().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->context().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->context().begin();
          it != this->context().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<ResponsePacket_ContextEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(context_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            7, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<ResponsePacket_ContextEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->context().begin();
          it != this->context().end(); ++it) {
        entry.reset(context_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            7, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:xy.ResponsePacket)
}

::google::protobuf::uint8* ResponsePacket::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:xy.ResponsePacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 iVersion = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->iversion(), target);
  }

  // optional uint32 iRequestId = 2;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->irequestid(), target);
  }

  // optional uint32 cPacketType = 3;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->cpackettype(), target);
  }

  // optional bytes sBuffer = 4;
  if (cached_has_bits & 0x00000001u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->sbuffer(), target);
  }

  // optional int32 iRetCode = 5;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->iretcode(), target);
  }

  // optional string sRetDesc = 6;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sretdesc().data(), static_cast<int>(this->sretdesc().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "xy.ResponsePacket.sRetDesc");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->sretdesc(), target);
  }

  // map<string, string> context = 7;
  if (!this->context().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormat::SERIALIZE,
          "xy.ResponsePacket.ContextEntry.key");
        ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormat::SERIALIZE,
          "xy.ResponsePacket.ContextEntry.value");
      }
    };

    if (deterministic &&
        this->context().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->context().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->context().begin();
          it != this->context().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<ResponsePacket_ContextEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(context_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       7, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<ResponsePacket_ContextEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->context().begin();
          it != this->context().end(); ++it) {
        entry.reset(context_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       7, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xy.ResponsePacket)
  return target;
}

size_t ResponsePacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xy.ResponsePacket)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // map<string, string> context = 7;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->context_size());
  {
    ::std::unique_ptr<ResponsePacket_ContextEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->context().begin();
        it != this->context().end(); ++it) {
      entry.reset(context_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  if (_has_bits_[0 / 32] & 63u) {
    // optional bytes sBuffer = 4;
    if (has_sbuffer()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->sbuffer());
    }

    // optional string sRetDesc = 6;
    if (has_sretdesc()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sretdesc());
    }

    // optional uint32 iVersion = 1;
    if (has_iversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->iversion());
    }

    // optional uint32 iRequestId = 2;
    if (has_irequestid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->irequestid());
    }

    // optional uint32 cPacketType = 3;
    if (has_cpackettype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->cpackettype());
    }

    // optional int32 iRetCode = 5;
    if (has_iretcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->iretcode());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResponsePacket::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:xy.ResponsePacket)
  GOOGLE_DCHECK_NE(&from, this);
  const ResponsePacket* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ResponsePacket>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:xy.ResponsePacket)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:xy.ResponsePacket)
    MergeFrom(*source);
  }
}

void ResponsePacket::MergeFrom(const ResponsePacket& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:xy.ResponsePacket)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  context_.MergeFrom(from.context_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_sbuffer();
      sbuffer_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sbuffer_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_sretdesc();
      sretdesc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sretdesc_);
    }
    if (cached_has_bits & 0x00000004u) {
      iversion_ = from.iversion_;
    }
    if (cached_has_bits & 0x00000008u) {
      irequestid_ = from.irequestid_;
    }
    if (cached_has_bits & 0x00000010u) {
      cpackettype_ = from.cpackettype_;
    }
    if (cached_has_bits & 0x00000020u) {
      iretcode_ = from.iretcode_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ResponsePacket::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:xy.ResponsePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResponsePacket::CopyFrom(const ResponsePacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xy.ResponsePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResponsePacket::IsInitialized() const {
  return true;
}

void ResponsePacket::Swap(ResponsePacket* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ResponsePacket::InternalSwap(ResponsePacket* other) {
  using std::swap;
  context_.Swap(&other->context_);
  sbuffer_.Swap(&other->sbuffer_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  sretdesc_.Swap(&other->sretdesc_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(iversion_, other->iversion_);
  swap(irequestid_, other->irequestid_);
  swap(cpackettype_, other->cpackettype_);
  swap(iretcode_, other->iretcode_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ResponsePacket::GetMetadata() const {
  protobuf_common_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_common_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace xy
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::xy::Info* Arena::CreateMaybeMessage< ::xy::Info >(Arena* arena) {
  return Arena::CreateInternal< ::xy::Info >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::xy::RequestPacket_ContextEntry_DoNotUse* Arena::CreateMaybeMessage< ::xy::RequestPacket_ContextEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::xy::RequestPacket_ContextEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::xy::RequestPacket* Arena::CreateMaybeMessage< ::xy::RequestPacket >(Arena* arena) {
  return Arena::CreateInternal< ::xy::RequestPacket >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::xy::ResponsePacket_ContextEntry_DoNotUse* Arena::CreateMaybeMessage< ::xy::ResponsePacket_ContextEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::xy::ResponsePacket_ContextEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::xy::ResponsePacket* Arena::CreateMaybeMessage< ::xy::ResponsePacket >(Arena* arena) {
  return Arena::CreateInternal< ::xy::ResponsePacket >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
